
MESSAGE( STATUS "Updating git revision" )

SET( GIT_CMD    git )

# Get the current working branch
execute_process(
  COMMAND ${GIT_CMD} rev-parse --abbrev-ref HEAD
  WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
  RESULT_VARIABLE GIT_OK
  OUTPUT_VARIABLE GIT_BRANCH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

if( NOT( ${GIT_OK} EQUAL 0 ) )
	file( STRINGS ${CMAKE_CURRENT_LIST_DIR}/../VERSION D6_VERSION )
	list( GET D6_VERSION 0 D6_VERSION_BRANCH )
	SET( GIT_BRANCH ${D6_VERSION_BRANCH} )
endif()

# Get the latest abbreviated commit hash of the working branch
execute_process(
  COMMAND ${GIT_CMD} log -1 --format=%h
  WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
  RESULT_VARIABLE GIT_OK
  OUTPUT_VARIABLE GIT_COMMIT_HASH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

if( NOT( ${GIT_OK} EQUAL 0 ) )
	list( GET D6_VERSION 1 D6_VERSION_HASH )
	SET( GIT_COMMIT_HASH ${D6_VERSION_HASH} )
endif()

if( ${CMAKE_VERSION} VERSION_GREATER 3.0.0 )
  string(TIMESTAMP COMPILE_TIME "%Y-%m-%d %H:%M")
endif()

configure_file(${TEMPLATE} ${OUTPUT})

